name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * 0' # Runs once a week at midnight on Sunday
  workflow_dispatch: # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Git and Fetch Upstream
      - name: Set up Git and Fetch Upstream
        run: |
          git remote add upstream https://github.com/dayanch96/YTLite.git
          git fetch upstream

      # Step 3: Check if the branch is up-to-date and merge if needed
      - name: Merge Upstream Changes
        run: |
          git checkout main
          merge_result=$(git merge --ff-only upstream/main || echo 'merge_failed')
          if [ "$merge_result" = "merge_failed" ]; then
            echo "Merged changes from upstream."
            git push origin main
          else
            echo "::warning ::Fork is already up-to-date. No changes to sync."
          fi
