name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * 0' # Runs once a week at midnight on Sunday
  workflow_dispatch: # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Git and Fetch Upstream
      - name: Set up Git and Fetch Upstream
        run: |
          git remote add upstream https://github.com/dayanch96/YTLite.git
          git fetch upstream

      # Step 3: Check if the branch is up-to-date and merge if needed
      - name: Merge Upstream Changes
        id: merge
        continue-on-error: true
        run: |
          git checkout main
          git merge --ff-only upstream/main
          
      # Step 4: Check if merge was needed
      - name: Check merge result
        if: steps.merge.outcome == 'failure'
        run: |
          echo "Fork is up-to-date. No changes to sync."
          echo "::warning ::Fork is already up-to-date. No changes to sync."

      - name: Push changes if merged
        if: steps.merge.outcome != 'failure'
        run: |
          echo "Merged changes from upstream."
          git push origin main
