import requests
from datetime import datetime

def get_ipa_size(download_url):
    """Get the size of the IPA file from the provided download URL."""
    try:
        # Send a request to the URL and get the headers to fetch the content length
        response = requests.head(download_url)
        
        # Check if the response is successful
        if response.status_code == 200:
            # Return the size of the file in bytes
            return int(response.headers.get('Content-Length', 0))
        else:
            print(f"Error fetching IPA file size from {download_url}. Status code: {response.status_code}")
            return 0
    except requests.RequestException as e:
        print(f"Error during request: {e}")
        return 0

def make_new_version(version, description, download_url, app_data):
    """Update app data with the new version information, setting the current date as version date."""
    # Get the current date and time in ISO format
    version_date = datetime.utcnow().isoformat() + "Z"
    
    # Get the size of the IPA file
    ipa_size = get_ipa_size(download_url)
    
    # Update the app data with the new version details
    app_data['version'] = version
    app_data['versionDate'] = version_date
    app_data['versionDescription'] = description
    app_data['downloadURL'] = download_url
    app_data['size'] = ipa_size  # Update the size of the IPA file
    
    # Optionally, update the localized description
    app_data['localizedDescription'] = description
    
    return app_data

# Example app data (from your input)
app_data = {
    "name": "YouTube Plus",
    "bundleIdentifier": "com.YouTubePlus.YTPlus",
    "developerName": "YouTubePlus Team",
    "version": "5.1",
    "versionDate": "2024-12-22T00:00:00Z",
    "versionDescription": "YouTube Plus version 5.1 brings enhanced features for a more enjoyable YouTube experience, including ad-blocking, background play, and additional customization options.",
    "beta": False,
    "size": 5100000,
    "localizedDescription": "YouTube Plus (YTPlus) offers an improved version of the official YouTube app with additional features like ad-blocking, background playback, and more.",
    "iconURL": "https://raw.githubusercontent.com/Taftle10/YTLite/refs/heads/main/logo.png",
    "tintColor": "FF0000",
    "downloadURL": "https://github.com/Taftle10/YTLite/releases/download/Release/YouTubePlus_5.1.ipa",
    "screenshotURLs": [
        "https://github.com/Taftle10/YTLite/raw/main/Resources/scr1.jpg?raw=true",
        "https://github.com/Taftle10/YTLite/raw/main/Resources/scr2.jpg?raw=true",
        "https://github.com/Taftle10/YTLite/blob/main/Resources/scr3.jpg?raw=true"
    ],
}

# Example to create a new version (5.2)
new_version = "5.2"
new_description = "YouTube Plus version 5.2 introduces new features, bug fixes, and performance improvements."
new_download_url = "https://github.com/Taftle10/YTLite/releases/download/Release/YouTubePlus_5.2.ipa"

# Create a new version and update the app data
updated_app_data = make_new_version(new_version, new_description, new_download_url, app_data)

# Output the updated app data
print(updated_app_data)
