name: Update Version

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Get the size of the download file
      - name: Get download file size
        id: file_size
        run: |
          # Get the download file URL from the JSON file or input
          DOWNLOAD_URL="https://github.com/Taftle10/YTLite/releases/download/Release/YouTubePlus_5.1.ipa"
          
          # Download the file and get its size
          FILE_SIZE=$(curl -sI "$DOWNLOAD_URL" | grep -i "Content-Length" | awk '{print $2}' | tr -d '\r')
          
          echo "File size: $FILE_SIZE bytes"
          echo "FILE_SIZE=$FILE_SIZE" >> $GITHUB_ENV

      # Update version metadata with the new file size
      - name: Update version metadata
        run: |
          # Path to the metadata file
          VERSION_FILE="repo.json"
          
          # Set the new values
          VERSION="5.1"
          VERSION_DATE="2024-12-22T00:00:00Z"
          VERSION_DESCRIPTION="YouTube Plus version 5.1 brings enhanced features for a more enjoyable YouTube experience, including ad-blocking, background play, and additional customization options."
          DOWNLOAD_URL="https://github.com/Taftle10/YTLite/releases/download/Release/YouTubePlus_5.1.ipa"
          ICON_URL="https://raw.githubusercontent.com/Taftle10/YTLite/refs/heads/main/logo.png"
          SCREENSHOT_URLS='[
            "https://github.com/Taftle10/YTLite/raw/main/Resources/scr1.jpg?raw=true",
            "https://github.com/Taftle10/YTLite/raw/main/Resources/scr2.jpg?raw=true",
            "https://github.com/Taftle10/YTLite/blob/main/Resources/scr3.jpg?raw=true"
          ]'
          SIZE=$FILE_SIZE

          # Create a new version metadata JSON object
          jq '.name = "YouTube Plus" |
              .bundleIdentifier = "com.YouTubePlus.YTPlus" |
              .developerName = "YouTubePlus Team" |
              .version = "'$VERSION'" |
              .versionDate = "'$VERSION_DATE'" |
              .versionDescription = "'$VERSION_DESCRIPTION'" |
              .beta = false |
              .size = '$SIZE' |
              .localizedDescription = "YouTube Plus (YTPlus) offers an improved version of the official YouTube app with additional features like ad-blocking, background playback, and more." |
              .iconURL = "'$ICON_URL'" |
              .tintColor = "FF0000" |
              .downloadURL = "'$DOWNLOAD_URL'" |
              .screenshotURLs = '$SCREENSHOT_URLS' ' $VERSION_FILE > updated_repo.json

          # Rename the updated file back to the original
          mv updated_repo.json $VERSION_FILE

      # Commit and push changes back to the repository
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "github-actions"
          author_email: "github-actions@github.com"
          message: "Update version 5.1 metadata with new download file size and URL"
          add: "repo.json"
