name: Update App Details

on:
  workflow_dispatch:
    inputs:
      addRelease:
        description: 'Add a new app release'
        required: false
        type: boolean
      releaseVersion:
        description: 'Version of the new release'
        required: false
        type: string
      releaseDate:
        description: 'Date of the new release'
        required: false
        type: string
      releaseDescription:
        description: 'Description of the new release'
        required: false
        type: string
      releaseDownloadLink:
        description: 'Download link for the new release'
        required: false
        type: string

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update JSON file
        run: |
          # Path to the JSON file
          FILE_PATH="repo.json"
          
          # Read the current JSON data
          JSON=$(cat $FILE_PATH)

          # Add Release
          if [ "${{ github.event.inputs.addRelease }}" = "true" ]; then
            # Format the date properly
            formatted_date=$(date -d "${{ github.event.inputs.releaseDate }}" --utc +"%Y-%m-%dT%H:%M:%SZ")

            # Add the release data to the JSON structure
            JSON=$(echo "$JSON" | jq --arg version "${{ github.event.inputs.releaseVersion }}" \
                                      --arg date "$formatted_date" \
                                      --arg description "${{ github.event.inputs.releaseDescription }}" \
                                      --arg downloadLink "${{ github.event.inputs.releaseDownloadLink }}" \
                                      '.apps[0].versions += [{
                                        "version": $version,
                                        "date": $date,
                                        "localizedDescription": $description,
                                        "downloadURL": $downloadLink
                                      }]')
          fi

          # Save the updated JSON back to the file
          echo "$JSON" > $FILE_PATH

      - name: Commit updated JSON
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Update app details'
          add: 'repo.json'

      - name: Push changes
        run: git push
