name: Update Version

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter the new version number'
        required: true
        default: '5.1'
      version_description:
        description: 'Enter the new version description'
        required: true
        default: 'YouTube Plus version 5.1 brings enhanced features for a more enjoyable YouTube experience, including ad-blocking, background play, and additional customization options.'
      download_url:
        description: 'Enter the new download file URL'
        required: true
        default: 'https://github.com/Taftle10/YTLite/releases/download/Release/YouTubePlus_5.1.ipa'

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Get the current date and time for the versionDate
      - name: Get current date and time
        id: current_time
        run: |
          VERSION_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "VERSION_DATE=$VERSION_DATE" >> $GITHUB_ENV

      # Get the size of the download file
      - name: Get download file size
        id: file_size
        run: |
          # Get the download file URL from the input
          DOWNLOAD_URL="${{ github.event.inputs.download_url }}"
          
          # Download the file and get its size
          FILE_SIZE=$(curl -sI "$DOWNLOAD_URL" | grep -i "Content-Length" | awk '{print $2}' | tr -d '\r')
          
          echo "File size: $FILE_SIZE bytes"
          echo "FILE_SIZE=$FILE_SIZE" >> $GITHUB_ENV

      # Add new version metadata to the JSON file
      - name: Add new version metadata
        run: |
          # Path to the metadata file
          VERSION_FILE="repo.json"
          
          # Set the new values
          VERSION="${{ github.event.inputs.version }}"
          VERSION_DATE="$VERSION_DATE"
          VERSION_DESCRIPTION="${{ github.event.inputs.version_description }}"
          DOWNLOAD_URL="${{ github.event.inputs.download_url }}"
          ICON_URL="https://raw.githubusercontent.com/Taftle10/YTLite/refs/heads/main/logo.png"
          SCREENSHOT_URLS='[
            "https://github.com/Taftle10/YTLite/raw/main/Resources/scr1.jpg?raw=true",
            "https://github.com/Taftle10/YTLite/raw/main/Resources/scr2.jpg?raw=true",
            "https://github.com/Taftle10/YTLite/blob/main/Resources/scr3.jpg?raw=true"
          ]'
          SIZE=$FILE_SIZE

          # Create a new version metadata entry
          NEW_VERSION_ENTRY=$(jq -n \
            --arg version "$VERSION" \
            --arg versionDate "$VERSION_DATE" \
            --arg versionDescription "$VERSION_DESCRIPTION" \
            --arg downloadURL "$DOWNLOAD_URL" \
            --arg iconURL "$ICON_URL" \
            --arg screenshotURLs "$SCREENSHOT_URLS" \
            --arg size "$SIZE" \
            '{
              name: "YouTube Plus",
              bundleIdentifier: "com.YouTubePlus.YTPlus",
              developerName: "YouTubePlus Team",
              version: $version,
              versionDate: $versionDate,
              versionDescription: $versionDescription,
              beta: false,
              size: ($size | tonumber),
              localizedDescription: "YouTube Plus (YTPlus) offers an improved version of the official YouTube app with additional features like ad-blocking, background playback, and more.",
              iconURL: $iconURL,
              tintColor: "FF0000",
              downloadURL: $downloadURL,
              screenshotURLs: ($screenshotURLs | fromjson)
            }')

          # Add the new version entry to the existing JSON file
          jq --argjson newVersionEntry "$NEW_VERSION_ENTRY" \
             '.versions += [$newVersionEntry]' \
             $VERSION_FILE > updated_repo.json

          # Rename the updated file back to the original
          mv updated_repo.json $VERSION_FILE

      # Commit and push changes back to the repository
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "github-actions"
          author_email: "github-actions@github.com"
          message: "Add new version ${{ github.event.inputs.version }} metadata"
          add: "repo.json"
